### ISSUE TITLE
Plugin name / Table prefix

### ISSUE THREAD

**Issue by Dagefoerde** [learnweb/moodle-tool_cleanupcourses#1]
I enabled Travis CI for this project out of curiosity. Everything looks good, except one complaint:
> ❌ In db/install.xml, failed to find table prefixes local_course_deprovision

... which is true, since local_coursedeprov does not obviously relate to this plugin :yum: 

On that note, – and to avoid renaming/refactoring everything multiple times – I'd like to suggest to rename this plugin and change its plugin type in accordance with our other effort (deprovisioning of users):
`moodle-tool_deprovisioncourses`

This way, all "deprovisioning" plugins would be located next to each other in alphabetical sorting:
```
- moodle-tool_deprovisioncourses
- moodle-tool_deprovisionusers
```

**Comment by tobiasreischmann** [comment]
The problem, why I abbreviated the database table name, is that moodle or something else has a limit on database table length. ;)
We definitely can rename the plugins as you suggested.

**Comment by Dagefoerde** [comment]
Okay, Moodle seems to have some weird name limits due to restrictions of Oracle DB... Well, we have to deal with it.

Also, I just realised that our other plugin is an admin tool, so I updated the above post. This should be `moodle-tool_deprovisioncourses`. Well, this saves one character but is still very long. 23 chars for the plugin name.

Maybe we should go for something shorter altogether, e.g. `moodle-tool_cleanupcourses` (19 chars)?

**Comment by tobiasreischmann** [comment]
I also thought about the plugin type. Since the functionality the plugin offers is not solely restricted to be accessed by admins, I decided to make a local plugin.

**Comment by Dagefoerde** [comment]
I agree, but that doesn't seem to be a criterion for Moodle. Cf. [Recycle bin](https://github.com/moodle/moodle/blob/master/admin/tool/recyclebin/index.php), which is actually mostly focused towards non-admins, but an admin tool nevertheless. If I recall correctly, this was a local plugin when it was a 3rd-party plugin, but since its integration into core it is an admin tool.

**Comment by tobiasreischmann** [comment]
Changed to admin tool
