### ISSUE TITLE
CourseLifeCycle - Overview

### ISSUE THREAD

**Issue by tobiasreischmann** [learnweb/moodle-tool_cleanupcourses#8]
We could offer a central page for teachers, which is reachable through the administration menu. On this page the teachers get status information about all their courses. Additionally, there they can trigger actions on each course (like keeping the course when it is about to be deleted). Another action could be to trigger a process, which copies the course into the next semester. 
However, this brings some problems, since then two processes might be running in parallel. This might cause a course being deleted, although it should be copied at the same time.

**Comment by Dagefoerde** [comment]
Fixed during Learnweb project days (in `develop` for now). `view.php` offers this page. It needs some further work that will be reflected in new issues.
